### ISSUE TITLE
Registration Screen

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#19]
- [x] 1. For all the media , we are not getting the Data and Base64 tags. e.g. we should get "**data:image/jpeg;base64,**/9j/4AAQSkZJRgAB", but we are only getting "**/9j/4AAQSkZJRgAB**"

- [x] 2. The Date formats all across the APP are expected in YYYY-MM-DD format and we are receiving DD/MM/YYYY . This is applicable all across the APP.

- [x] 3. While taking the Company CR picture, the UI is completely different to other interfaces for taking pictures.

- [x] 4. After taking the picture, there should be an option for rotate

- [x] 5. Looks like the APP is resizing the CR Document to a very low resolution 800x600.

- [x] 6. for Sponsor Front side we are receiving Employee Front Side. 

- [x] 7. Signature space is not sufficient, can we do portrait, at the time of  taking the signature

- [x] 8. When clicked Register, immediately Busy / procesing overlay is not shown. There is a delay due to which the user can click the register button again. Hence Overlay should be immediate with out any delay. This is applicable all across the APP.

- [x] 9. If the response is Flash, then there is every chance that the user will miss it or could not read completely, Hence the response should be shown in a model window instead of Flash. This is applicable all across the APP unless otherwise specified particularly.

- [x] 10. I have tapped register button multiple times and multiple requests are received. Once the button is pressed, then it should be disabled until the response is received from server.

- [ ] 11.  After successful signup, the APP is taking the user to login screen. But a successful registration message should be shown along with the request ID and company contact details. Final Response of the RegisterDealer API will return RequestId for this purpose.

- [x] 12. Email fields are optional all across the APP.

- [x] 13. Company Information all the fields are optional.

- [x] 14. In all the bar codes scanning, all across the APP, the camera preview is coming as stretched and it is normal. Please have a look.

- [x]  15. When QR Is scanned for CR Number field, then it will return a URL something like "https://business.gov.om/wps/PA_OSS3_Portal/external.htm?target=viewCompany&crNumber=1253970", but you need to take only the number after crNumber=

**Comment by mobiloitte-quality** [comment]
1. For all the media , we are not getting the Data and Base64 tags. e.g. we should get "data:image/jpeg;base64,/9j/4AAQSkZJRgAB", but we are only getting "/9j/4AAQSkZJRgAB"
**Mobiloitte Comment:** we are sending image into base64 format

 2. The Date formats all across the APP are expected in YYYY-MM-DD format and we are receiving DD/MM/YYYY . This is applicable all across the APP.
**Mobiloitte Comment:**  done

 3. While taking the Company CR picture, the UI is completely different to other interfaces for taking pictures.
**Mobiloitte Comment:** we are opening default camera to take picture or upload picture from gallary

 4. After taking the picture, there should be an option for rotate
**Mobiloitte Comment:**  It already working on the time of crop image screen.

 5. Looks like the APP is resizing the CR Document to a very low resolution 800x600.
**Mobiloitte Comment:** Done, now resolution is 1080x720

 6. for Sponsor Front side we are receiving Employee Front Side.
**Mobiloitte Comment:**  done

 7. Signature space is not sufficient, can we do portrait, at the time of taking the signature
**Mobiloitte Comment:** done


 8. When clicked Register, immediately Busy / procesing overlay is not shown. There is a delay due to which the user can click the register button again. Hence Overlay should be immediate with out any delay. This is applicable all across the APP.
**Mobiloitte Comment:**  done

 9. If the response is Flash, then there is every chance that the user will miss it or could not read completely, Hence the response should be shown in a model window instead of Flash. This is applicable all across the APP unless otherwise specified particularly.
**Mobiloitte Comment:** :done

 10. I have tapped register button multiple times and multiple requests are received. Once the button is pressed, then it should be disabled until the response is received from server.
**Mobiloitte Comment:** It's working fine ,but in the case of failure of service u can again tapped on register button.other wise u navigate on next screen.If you find any problem regarding this, please send video.

 11. After successful signup, the APP is taking the user to login screen. But a successful registration message should be shown along with the request ID and company contact details. Final Response of the RegisterDealer API will return RequestId for this purpose.
**Mobiloitte Comment:** Done

**Comment by mjov** [comment]
Points 8&10 above seems to be talking about the same issue, hence after testing 1.7 version, I still see the problem:

- after confirming <register>: the button should be made inactive  (Change the transparency)
- after confirming <register>: there is a long delay before 'loading' window shows 
- app must indicate to the user that registration process is ongoing immediately after pressing 
 <register> button

general note for all backend processing/verifications:  
- app must indicate to the user that there is a verification/registration process in the background, hence instead of pop-up-window "loading", app should show the window that displays appropriate text content. For registration, it should say "Submitting Registration", for verification "Verifying", for activation "Activating SIM card", etc...

**Comment by mobiloitte-quality** [comment]
@pmadiset Please find the inline comments on the issues posted by you:-

 - For all the media , we are not getting the Data and Base64 tags. e.g. we should get "data:image/jpeg;base64,/9j/4AAQSkZJRgAB", but we are only getting "/9j/4AAQSkZJRgAB"
**Mobiloitte Comment:** Done

- While taking the Company CR picture, the UI is completely different to other interfaces for taking pictures.
**Mobiloitte Comment**: Done

- After taking the picture, there should be an option for rotate
**Mobiloitte Comment:** Added rotate feature, working fantastic! 

- Looks like the APP is resizing the CR Document to a very low resolution 800x600.
**Mobiloitte Comment:** Done, now resolution is 1080x720

- I have tapped register button multiple times and multiple requests are received. Once the button is pressed, then it should be disabled until the response is received from server.
**Mobiloitte Comment:**  The behavior of the button is like- when you add the requirements and tap on "Register" button, processing message displays, until it process the "Register" button is inactive, and as soon as the processing is done the next screen opens. 

- After successful signup, the APP is taking the user to login screen. But a successful registration message should be shown along with the request ID and company contact details. Final Response of the RegisterDealer API will return RequestId for this purpose.
**Mobiloitte Comment:** Done

@mjov Please find the inline comments on the issues posted by you:-

Points 8&10 above seems to be talking about the same issue, hence after testing 1.7 version, I still see the problem:

- after confirming : the button should be made inactive (Change the transparency)
**Mobiloitte Comment:** Firstly we were using "loading" as a toast/ (Flash message), and as per your request, we've added the change this across the APP.  

- after confirming : the button should be made inactive (Change the transparency)
   **Mobiloitte Comment:** Done

- after confirming : there is a long delay before 'loading' window shows app must indicate to the user that registration process is ongoing immediately after pressing button. 
   **Mobiloitte Comment:** Done

general note for all backend processing/verifications:
app must indicate to the user that there is a verification/registration process in the background, hence instead of pop-up-window "loading", app should show the window that displays appropriate text content. For registration, it should say "Submitting Registration", for verification "Verifying", for activation "Activating SIM card", etc...
**Mobiloitte Comment:** Firstly we were using "loading" as a toast/ (Flash message), and as per your request, we've added the change this across the APP.

**Comment by mobiloitte-quality** [comment]
@pmadiset Please look into the below issues as I missed to mention above. 

12. Email fields are optional all across the APP.
**Mobiloitte Comment:** Done

 13. Company Information all the fields are optional.
**Mobiloitte Comment:** Not Done

 14. In all the bar codes scanning, all across the APP, the camera preview is coming as stretched and it is normal. Please have a look.
**Mobiloitte Comment:** Scanner is able to fetch the data from the barcode while capturing the barcode.

 15. When QR Is scanned for CR Number field, then it will return a URL something like "https://business.gov.om/wps/PA_OSS3_Portal/external.htm?target=viewCompany&crNumber=1253970", but you need to take only the number after crNumber=
**Mobiloitte Comment:** Done

**Comment by mjov** [comment]
APP Ver1.8
Hi;
- [ ] we seem lost now the option of uploading the document on CR Copy section
