### ISSUE TITLE
Notifications Page

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#34]
- [x]  The scrolling is not smooth. When the APP gets further notifications, 1) an over lay comes saying busy 2) The screen will become white 3) All the notification items gets animated. Due to this user will loose the track. The scrolling should be smooth and should happen in the background. Already displayed items should not be animated.

- [x] Please present a scroll bar in all such pages 1) Notifications 2) Transaction History 3) Wallet History. etc

**Comment by mobiloitte-quality** [comment]
The scrolling is not smooth. When the APP gets further notifications, 

1) an over lay comes saying busy 

2) The screen will become white 

3) All the notification items gets animated. Due to this user will loose the track. The scrolling should be smooth and should happen in the background. Already displayed items should not be animated.

**Comment**: Need to be discussed with you

**Comment by mobiloitte-quality** [comment]
Please present a scroll bar in all such pages 1) Notifications 2) Transaction History 3) Wallet History. etc 
Done
