### ISSUE TITLE
Subscription Page

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#36]
### When tapped to subscribe
- [x]  Background screen is moving up because of keypad. It should be static

- [x] There is no cancel button 

- [x] After entering the number and tapping OK, another confirmation dialog opens. But on this dialog, the customer mobile number should be displayed.

- [x]  The Font on Cancel and Confirm buttons is not standard.

- [x] MobileNumber is not passed to the Subscription API

### Display of Bundles

- [x] Display of Bundle validity should be center aligned with the circle.

**Comment by mobiloitte-quality** [comment]
**When tapped to subscribe**
 Background screen is moving up because of keypad. It should be static
**Comment**: Done

 There is no cancel button
**Comment**: Done

 After entering the number and tapping OK, another confirmation dialog opens. But on this dialog, the customer mobile number should be displayed.
**Comment**: Done

 The Font on Cancel and Confirm buttons is not standard.
**Comment**: We are using the same font that was shared you and its looking fine. Please suggest what your exact concern on this. 

 MobileNumber is not passed to the Subscription API
**Comment**: Done

**Comment by mobiloitte-quality** [comment]
@pmadiset please close
