### ISSUE TITLE
Other Issues

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#40]
- [x]  Right now server has no clue what version of the APP is being used. Hence request you to submit below two values in GetAppSettings  along with CurrentVersion 1) AppVersion --> Version of the application that is normally seen on Settings screen 2) MRZVersion -->Version of Regular MRZ Library.

- [x] Please remove the Red Border for Signature

- [x] Session Expiry on Server side (due to login from other device). APP on Old device should logout.

- [x] The + icon on Agents page for adding new Agents is very small. Please make it considerably visible and tappable.

- [x]  When SIM scan returns MSISDN, IMSI is getting cleared.

- [x] When Activation form is filled half way, and moving out of this screen will clear the form.

- [x] For Page Create Agent Manual. Only Employee is mandatory and not company. Please make company optional.

**Comment by mobiloitte-quality** [comment]
Right now server has no clue what version of the APP is being used. Hence request you to submit below two values in GetAppSettings along with CurrentVersion 1) AppVersion --> Version of the application that is normally seen on Settings screen 2) MRZVersion -->Version of Regular MRZ Library.
Comment: Done

 Please remove the Red Border for Signature
Comment: Done

 Session Expiry on Server side (due to login from other device). APP on Old device should logout.
Comment: This was conveyed earlier. We have implemented session management for same device user logout after every 10 minutes. If you want change we can share effort for this point. 


 When SIM scan returns MSISDN, IMSI is getting cleared.
Comment: Not clear

 When Activation form is filled half way, and moving out of this screen will clear the form.
Comment: done

 For Page Create Agent Manual. Only Employee is mandatory and not company. Please make company optional.
Comment: Done

**Comment by mobiloitte-quality** [comment]
When Activation form is filled half way, and moving out of this screen will clear the form.
Comment: This is time consuming task,  required extra effort.

**Comment by pmadiset** [comment]
Please let us know, by what date this can be fixed. We need this to be fixed before we go live on 15th Oct.

**Comment by mobiloitte-quality** [comment]
This point is changes, we will work on it  after approval and payment of running milestone.
