### ISSUE TITLE
My Details & Agent Details Page

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#45]
- [x]  The page first display dummy information and then gets the information from API and replaces on the page. This is wrong. Initially the page should be blank and page should render after information is pulled form server.

- [x] Up on clicking edit, instead of opening the Dealer Information heading, open Company Heading.

- [x] API returns data.Employee.picture, this should be presented in the image picture place holder.

**Comment by mobiloitte-quality** [comment]
The page first display dummy information and then gets the information from API and replaces on the page. This is wrong. Initially the page should be blank and page should render after information is pulled form server.
Comment: Done

Up on clicking edit, instead of opening the Dealer Information heading, open Company Heading.
Comment: Done

API returns data.Employee.picture, this should be presented in the image picture place holder.
Comment: We have shown in my detail, in agent detail we are not getting pic in Api.
